## Part 1: Preprocessing

In [117]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [118]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [119]:
# Create y_df with the Attrition and Department columns
y_df= attrition_df[['Attrition', 'Department']]
#

In [120]:
y_df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [121]:
y_df["Attrition"].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [122]:
attrition_df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [123]:
# Create a list of at least 10 column names to use as X data
list_of_columns = ['Age', 'DistanceFromHome',
       'Education', 'JobSatisfaction', 'NumCompaniesWorked', 'OverTime', 'StockOptionLevel','WorkLifeBalance',
       'YearsAtCompany', 'YearsSinceLastPromotion']
# Create X_df using your selected columns
X= attrition_df[list_of_columns]

# Show the data types for X_df
X.dtypes

Age                         int64
DistanceFromHome            int64
Education                   int64
JobSatisfaction             int64
NumCompaniesWorked          int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
dtype: object

In [124]:
X.head()

,Age,DistanceFromHome,Education,JobSatisfaction,NumCompaniesWorked,OverTime,StockOptionLevel,WorkLifeBalance,YearsAtCompany,YearsSinceLastPromotion
0,41,1,2,4,8,Yes,0,1,6,0
1,49,8,1,2,1,No,1,3,10,1
2,37,2,2,3,6,Yes,0,3,0,0
3,33,3,4,3,1,Yes,0,3,8,3
4,27,2,1,2,9,No,1,3,2,2

In [125]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test,y_df_train,y_df_test = train_test_split(X, y_df)

In [126]:
X_train.dtypes

Age                         int64
DistanceFromHome            int64
Education                   int64
JobSatisfaction             int64
NumCompaniesWorked          int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
dtype: object

In [127]:
X_test.dtypes

Age                         int64
DistanceFromHome            int64
Education                   int64
JobSatisfaction             int64
NumCompaniesWorked          int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
dtype: object

In [128]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
overtime_encoder= OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop='first')
overtime_encoder.fit(X_train[['OverTime']])
X_train["Overtime_Encoded"]= overtime_encoder.transform(np.array(X_train['OverTime']).reshape(-1, 1))
X_test["Overtime_Encoded"]= overtime_encoder.transform(np.array(X_test['OverTime']).reshape(-1, 1))
X_train= X_train.drop(columns=['OverTime'])
X_test= X_test.drop(columns=['OverTime'])

/opt/anaconda3/envs/CU_Phyton3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
/opt/anaconda3/envs/CU_Phyton3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [129]:
X_train.head()

,Age,DistanceFromHome,Education,JobSatisfaction,NumCompaniesWorked,StockOptionLevel,WorkLifeBalance,YearsAtCompany,YearsSinceLastPromotion,Overtime_Encoded
1359,34,3,1,4,3,0,2,4,0,1.0
167,30,5,3,4,2,1,3,10,7,0.0
677,49,8,2,2,4,1,2,26,1,0.0
557,35,2,4,1,2,1,4,1,0,0.0
1083,40,9,4,1,3,0,1,5,1,0.0

In [130]:
# Create a StandardScaler

s_scaler= StandardScaler()
# Fit the StandardScaler to the training data
s_scaler.fit(X_train)


# Scale the training and testing data
X_train_scaled = s_scaler.transform(X_train)
X_test_scaled = s_scaler.transform(X_test)

In [131]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop=None)

# Fit the encoder to the "Department" column in the training data
ohe.fit(np.array(y_df["Department"]).reshape(-1, 1))

# Create two new variables by applying the encoder to the training and testing data
y_scaled_train_department= ohe.transform(np.array(y_df_train['Department']).reshape(-1, 1))
y_scaled_test_department= ohe.transform(np.array(y_df_test['Department']).reshape(-1, 1))

In [132]:
# Create a OneHotEncoder for the Attrition column

ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore', drop=None)

# Fit the encoder to the "Department" column in the training data
ohe.fit(np.array(y_df["Attrition"]).reshape(-1, 1))

# Create two new variables by applying the encoder to the training and testing data
y_scaled_train_attrition= ohe.transform(np.array(y_df_train['Attrition']).reshape(-1, 1))
y_scaled_test_attrition= ohe.transform(np.array(y_df_test['Attrition']).reshape(-1, 1))

In [133]:
y_scaled_train_department

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [134]:
# Find the number of columns in the X training data.
X_train_scaled.shape[1]

# Create the input layer
input = layers.Input(shape=(X_train_scaled.shape[1],), name='input_layer')
# Create at least two shared layers
shared1 = layers.Dense(64, activation='relu', name='second_layer')(input)
shared2 = layers.Dense(128, activation='relu', name='third_layer')(shared1)

In [135]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(32, activation='softmax', name='department_hidden')(shared2)

# Create the output layer
department_output = layers.Dense(3, activation='sigmoid', name='department_output')(department_hidden)

In [136]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer

attrition_hidden = layers.Dense(32, activation='softmax', name='attrition_hidden')(shared2)
# Create the output layer
attition_output = layers.Dense(2, activation='sigmoid', name='attrition_output')(attrition_hidden)

In [137]:
# Create the model

model = Model(inputs=input, outputs=[department_output, attition_output])
# Compile the model
model.compile(optimizer='adam',
               loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'},
              metrics={'department_output': 'accuracy', 'attrition_output': 'accuracy'})

# Summarize the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ second_layer        │ (None, 64)        │        704 │ input_layer[0][0] │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ third_layer (Dense) │ (None, 128)       │      8,320 │ second_layer[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 32)        │      4,128 │ third_layer[0][0] │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 32)        │      4,128 │ third_layer[0][0] │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         99 │ department_hidde… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         66 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 17,445 (68.14 KB)

 Trainable params: 17,445 (68.14 KB)

 Non-trainable params: 0 (0.00 B)

In [138]:
# Train the model


model.fit(
    X_test_scaled,
    {'department_output': y_scaled_train_department, 'attrition_output': y_scaled_train_attrition},
    epochs=100,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - attrition_output_accuracy: 0.8326 - attrition_output_loss: 0.6839 - department_output_accuracy: 0.3692 - department_output_loss: 1.0936 - loss: 1.7783 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.6782 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 1.0741 - val_loss: 1.7439
Epoch 2/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8646 - attrition_output_loss: 0.6639 - department_output_accuracy: 0.5947 - department_output_loss: 1.0592 - loss: 1.7242 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.6640 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 1.0409 - val_loss: 1.6864
Epoch 3/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8536 - attrition_output_loss: 0.6416 - department_output_accuracy: 0.5916 - department_output_loss: 1.0202 - loss: 1.6615 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.6459 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 1.0052 - val_loss: 1.6195
Epoch 4/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8616 - attrition_output_loss: 0.6097 - department_output_accuracy: 0.6293 - department_output_loss: 0.9719 - loss: 1.5814 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.6270 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9772 - val_loss: 1.5616
Epoch 5/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8496 - attrition_output_loss: 0.5850 - department_output_accuracy: 0.6596 - department_output_loss: 0.9331 - loss: 1.5198 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.6108 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9632 - val_loss: 1.5235
Epoch 6/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8165 - attrition_output_loss: 0.5812 - department_output_accuracy: 0.6813 - department_output_loss: 0.9223 - loss: 1.5029 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5999 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9549 - val_loss: 1.4992
Epoch 7/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8647 - attrition_output_loss: 0.5463 - department_output_accuracy: 0.6213 - department_output_loss: 0.9071 - loss: 1.4546 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5944 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9494 - val_loss: 1.4849
Epoch 8/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8338 - attrition_output_loss: 0.5563 - department_output_accuracy: 0.6303 - department_output_loss: 0.9124 - loss: 1.4675 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5909 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9428 - val_loss: 1.4721
Epoch 9/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8322 - attrition_output_loss: 0.5527 - department_output_accuracy: 0.6424 - department_output_loss: 0.8903 - loss: 1.4429 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5880 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9371 - val_loss: 1.4610
Epoch 10/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8445 - attrition_output_loss: 0.5403 - department_output_accuracy: 0.5872 - department_output_loss: 0.9105 - loss: 1.4515 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5854 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9318 - val_loss: 1.4509
Epoch 11/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8601 - attrition_output_loss: 0.5274 - department_output_accuracy: 0.6068 - department_output_loss: 0.9026 - loss: 1.4283 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5830 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9269 - val_loss: 1.4413
Epoch 12/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8587 - attrition_output_loss: 0.5253 - department_output_accuracy: 0.5962 - department_output_loss: 0.8895 - loss: 1.4156 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5807 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9237 - val_loss: 1.4336
Epoch 13/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8318 - attrition_output_loss: 0.5361 - department_output_accuracy: 0.6125 - department_output_loss: 0.8924 - loss: 1.4291 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5787 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9190 - val_loss: 1.4249
Epoch 14/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8450 - attrition_output_loss: 0.5229 - department_output_accuracy: 0.6231 - department_output_loss: 0.8717 - loss: 1.3959 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5767 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9152 - val_loss: 1.4169
Epoch 15/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8213 - attrition_output_loss: 0.5362 - department_output_accuracy: 0.6225 - department_output_loss: 0.8722 - loss: 1.4101 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5747 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9121 - val_loss: 1.4097
Epoch 16/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8446 - attrition_output_loss: 0.5162 - department_output_accuracy: 0.5987 - department_output_loss: 0.8774 - loss: 1.3949 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5729 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9091 - val_loss: 1.4029
Epoch 17/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8619 - attrition_output_loss: 0.5043 - department_output_accuracy: 0.5902 - department_output_loss: 0.8732 - loss: 1.3755 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5711 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9066 - val_loss: 1.3965
Epoch 18/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8369 - attrition_output_loss: 0.5184 - department_output_accuracy: 0.6217 - department_output_loss: 0.8587 - loss: 1.3761 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5696 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9041 - val_loss: 1.3907
Epoch 19/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8160 - attrition_output_loss: 0.5289 - department_output_accuracy: 0.6207 - department_output_loss: 0.8563 - loss: 1.3848 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5683 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9017 - val_loss: 1.3852
Epoch 20/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8266 - attrition_output_loss: 0.5190 - department_output_accuracy: 0.6418 - department_output_loss: 0.8451 - loss: 1.3649 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5669 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8998 - val_loss: 1.3800
Epoch 21/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8499 - attrition_output_loss: 0.4991 - department_output_accuracy: 0.6123 - department_output_loss: 0.8519 - loss: 1.3530 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5656 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8979 - val_loss: 1.3750
Epoch 22/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8634 - attrition_output_loss: 0.4899 - department_output_accuracy: 0.5923 - department_output_loss: 0.8713 - loss: 1.3581 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5644 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8960 - val_loss: 1.3701
Epoch 23/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8522 - attrition_output_loss: 0.4901 - department_output_accuracy: 0.6267 - department_output_loss: 0.8402 - loss: 1.3355 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5634 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8941 - val_loss: 1.3655
Epoch 24/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8276 - attrition_output_loss: 0.5112 - department_output_accuracy: 0.6271 - department_output_loss: 0.8367 - loss: 1.3480 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5623 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8919 - val_loss: 1.3606
Epoch 25/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8317 - attrition_output_loss: 0.5079 - department_output_accuracy: 0.6228 - department_output_loss: 0.8421 - loss: 1.3410 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5613 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8902 - val_loss: 1.3562
Epoch 26/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8349 - attrition_output_loss: 0.5013 - department_output_accuracy: 0.6517 - department_output_loss: 0.8177 - loss: 1.3129 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5605 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8889 - val_loss: 1.3527
Epoch 27/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8470 - attrition_output_loss: 0.4895 - department_output_accuracy: 0.6133 - department_output_loss: 0.8646 - loss: 1.3479 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5597 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8883 - val_loss: 1.3498
Epoch 28/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - attrition_output_accuracy: 0.8385 - attrition_output_loss: 0.4905 - department_output_accuracy: 0.6062 - department_output_loss: 0.8486 - loss: 1.3407 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5589 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8881 - val_loss: 1.3474
Epoch 29/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8503 - attrition_output_loss: 0.4806 - department_output_accuracy: 0.5972 - department_output_loss: 0.8525 - loss: 1.3353 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5581 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8878 - val_loss: 1.3446
Epoch 30/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8588 - attrition_output_loss: 0.4754 - department_output_accuracy: 0.6636 - department_output_loss: 0.8053 - loss: 1.2748 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5574 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8866 - val_loss: 1.3410
Epoch 31/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8436 - attrition_output_loss: 0.4825 - department_output_accuracy: 0.6087 - department_output_loss: 0.8463 - loss: 1.3268 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5568 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8861 - val_loss: 1.3387
Epoch 32/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8397 - attrition_output_loss: 0.4865 - department_output_accuracy: 0.6396 - department_output_loss: 0.8133 - loss: 1.2933 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5562 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8861 - val_loss: 1.3366
Epoch 33/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8328 - attrition_output_loss: 0.4914 - department_output_accuracy: 0.6400 - department_output_loss: 0.8211 - loss: 1.3082 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5557 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8864 - val_loss: 1.3351
Epoch 34/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8529 - attrition_output_loss: 0.4735 - department_output_accuracy: 0.6237 - department_output_loss: 0.8400 - loss: 1.3084 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5553 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8871 - val_loss: 1.3339
Epoch 35/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8453 - attrition_output_loss: 0.4768 - department_output_accuracy: 0.6038 - department_output_loss: 0.8448 - loss: 1.3215 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5549 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8878 - val_loss: 1.3328
Epoch 36/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8238 - attrition_output_loss: 0.4930 - department_output_accuracy: 0.6184 - department_output_loss: 0.8474 - loss: 1.3442 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5546 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8876 - val_loss: 1.3309
Epoch 37/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8329 - attrition_output_loss: 0.4833 - department_output_accuracy: 0.5915 - department_output_loss: 0.8454 - loss: 1.3267 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5543 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8879 - val_loss: 1.3290
Epoch 38/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - attrition_output_accuracy: 0.8361 - attrition_output_loss: 0.4813 - department_output_accuracy: 0.6266 - department_output_loss: 0.8128 - loss: 1.2926 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5540 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8890 - val_loss: 1.3277
Epoch 39/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8424 - attrition_output_loss: 0.4684 - department_output_accuracy: 0.6235 - department_output_loss: 0.8114 - loss: 1.2831 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5540 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8901 - val_loss: 1.3272
Epoch 40/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8253 - attrition_output_loss: 0.4834 - department_output_accuracy: 0.6230 - department_output_loss: 0.8135 - loss: 1.3018 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5539 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8901 - val_loss: 1.3257
Epoch 41/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8673 - attrition_output_loss: 0.4413 - department_output_accuracy: 0.6340 - department_output_loss: 0.8081 - loss: 1.2444 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5536 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8896 - val_loss: 1.3234
Epoch 42/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8283 - attrition_output_loss: 0.4797 - department_output_accuracy: 0.6434 - department_output_loss: 0.7884 - loss: 1.2656 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5536 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8913 - val_loss: 1.3231
Epoch 43/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - attrition_output_accuracy: 0.8389 - attrition_output_loss: 0.4684 - department_output_accuracy: 0.6227 - department_output_loss: 0.8173 - loss: 1.2840 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5535 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8949 - val_loss: 1.3237
Epoch 44/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8523 - attrition_output_loss: 0.4508 - department_output_accuracy: 0.6167 - department_output_loss: 0.8199 - loss: 1.2741 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5533 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8944 - val_loss: 1.3218
Epoch 45/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8428 - attrition_output_loss: 0.4579 - department_output_accuracy: 0.6785 - department_output_loss: 0.7668 - loss: 1.2250 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5531 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8924 - val_loss: 1.3186
Epoch 46/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8464 - attrition_output_loss: 0.4567 - department_output_accuracy: 0.6222 - department_output_loss: 0.8089 - loss: 1.2649 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5530 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8933 - val_loss: 1.3174
Epoch 47/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8299 - attrition_output_loss: 0.4690 - department_output_accuracy: 0.6621 - department_output_loss: 0.7704 - loss: 1.2354 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5529 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8963 - val_loss: 1.3176
Epoch 48/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8298 - attrition_output_loss: 0.4718 - department_output_accuracy: 0.6300 - department_output_loss: 0.7944 - loss: 1.2624 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5526 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9001 - val_loss: 1.3189
Epoch 49/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8109 - attrition_output_loss: 0.4885 - department_output_accuracy: 0.6576 - department_output_loss: 0.7659 - loss: 1.2517 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5526 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8986 - val_loss: 1.3167
Epoch 50/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8501 - attrition_output_loss: 0.4466 - department_output_accuracy: 0.6878 - department_output_loss: 0.7576 - loss: 1.1972 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5527 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.8978 - val_loss: 1.3146
Epoch 51/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8291 - attrition_output_loss: 0.4682 - department_output_accuracy: 0.6157 - department_output_loss: 0.8063 - loss: 1.2754 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5530 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9005 - val_loss: 1.3157
Epoch 52/100
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8358 - attrition_output_loss: 0.4584 - department_output_accuracy: 0.5968 - department_output_loss: 0.8150 - loss: 1.2713 - val_attrition_output_accuracy: 0.8378 - val_attrition_output_loss: 0.5533 - val_department_output_accuracy: 0.6757 - val_department_output_loss: 0.9016 - val_loss: 1.3155
Epoch 53/100

In [140]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, {'department_output': y_scaled_test_department,'attrition_output': y_scaled_test_attrition,})
test_results

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - attrition_output_accuracy: 0.7837 - attrition_output_loss: 0.4699 - department_output_accuracy: 0.5809 - department_output_loss: 0.8697 - loss: 1.3408

[1.3523703813552856,
 0.8729045987129211,
 0.4715259373188019,
 0.7880434989929199,
 0.5679348111152649]

In [141]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {test_results[3]}")
print(f"Attrition Accuracy: {test_results[4]}")

Department Accuracy: 0.7880434989929199
Attrition Accuracy: 0.5679348111152649

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Yes, it is best metric to use. Because it was a very inbalanced data.
2. I used sigmoid and sofmax funtions for the output layers. Because department output had three features so I used softmax,  attrition output has 2 features(binary) I used sigmoid.
3. First, I can try to over or under sampling to the data since it was very in balance data. 
Secondly, we have been asked used 10 features, maybe I can include the more featues and run the model.